apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-demo
  namespace: database
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-manual
  hostPath:
    path: /home/ubuntu/data/postgres