apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
  namespace: kafka
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-manual
  hostPath:
    path: /home/ubuntu/data/kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-2
  namespace: kafka
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-manual
  hostPath:
    path: /home/ubuntu/data/kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-3
  namespace: kafka
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-manual
  hostPath:
    path: /home/ubuntu/data/kafka

