apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: docker.redpanda.com/redpandadata/console:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "3.135.202.131:30094"
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console-service
  namespace: kafka
spec:
  selector:
    app: redpanda-console
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
