apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
  annotations:
    description: "Using basic configuration for testing"
spec:
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: "2.3"
      log.retention.bytes: 1073741824
      log.retention.hours: 1
      log.retention.check.interval.ms: 300000
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: sdnprivate
        port: 9094
        type: nodeport
        tls: false
        # authentication:
        #   type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 30094
          brokers:
          - broker: 0
            advertisedHost: 3.135.202.131
            advertisedPort: 30091
            nodePort: 30091
          - broker: 1
            advertisedHost: 3.135.202.131
            advertisedPort: 30092
            nodePort: 30092
          - broker: 2
            advertisedHost: 3.135.202.131
            advertisedPort: 30093
            nodePort: 30093
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 512Mi
    storage:
      deleteClaim: true
      size: 5Gi
      type: persistent-claim
      class: kafka-manual
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
        # affinity:
        #   podAntiAffinity:
        #     requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #         - key: strimzi.io/name
        #           operator: In
        #           values:
        #           - demo-kafka
        #       topologyKey: kubernetes.io/hostname
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 1
    storage:
      deleteClaim: true
      size: 5Gi
      type: persistent-claim
      class: zookeeper-manual
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
        # affinity:
        #   podAntiAffinity:
        #     requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchExpressions:
        #         - key: strimzi.io/name
        #           operator: In
        #           values:
        #           - demo-zookeeper
        #       topologyKey: kubernetes.io/hostname
    resources:
      limits:
        cpu: "0.5"
        memory: 1Gi
      requests:
        cpu: "0.3"
        memory: 512Mi
  entityOperator:
    userOperator:
      resources:
        limits:
          cpu: "0.5"
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi
    topicOperator:
      resources:
        limits:
          cpu: "0.5"
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi
  