apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: demo-connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.5.0
  replicas: 1
  bootstrapServers: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  config:
    group.id: postgres-demo
    offset.storage.topic: demo-connect-cluster-offset
    config.storage.topic: demo-connect-cluster-config
    status.storage.topic: demo-connect-cluster-status
    # config.providers: secrets,configmaps
    # config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    # config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
    # # -1 means it will use the default replication factor configured in the broker
    # config.storage.replication.factor: -1
    # offset.storage.replication.factor: -1
    # status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: unibna/postgres-demo-connect:lastest
      pushSecret: unibna-docker
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: zip
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.4.0.Final/debezium-connector-postgres-2.4.0.Final-plugin.zip
            # sha512sum: -
  template:
    pod:
      securityContext:
        runAsUser: 0