apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: demo-debezium-postgres-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: demo-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: 3.135.202.131
    database.port: 30432
    database.user: "demo"
    database.password: "demo"
    database.dbname: "demo"
    database.server.name: "demo-debezium"
    topic.prefix: demo
    slot.name: "slot_debezium"
    plugin.name: "pgoutput"
    decimal.handling.mode: "double"
    include.schema.changes: "true" 
